# Parent Application for the dev environment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-env
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PierreBesson/argocd-gitops-env.git
    path: environment
    targetRevision: HEAD
    helm:
      valueFiles:
        - "values.yaml"
        - "values-local.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
